apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: production-http-issuer
  labels:
    {{- include "cluster-issuers.labels" . | nindent 4 }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: "ISRG Root X1"
    privateKeySecretRef:
      name: production-http-issuer
    solvers:
    - http01:
        ingress:
          class: nginx
