apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: staging-http-issuer
  labels:
    {{- include "cert-manager-umbrella.labels" . | nindent 4 }}
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: staging-http-issuer
    solvers:
      - http01:
          ingress:
            class: nginx
